---
# defaults file for zabbix-agent

zabbix_agent_version: "3.4.3"

zabbix_agent_repo_url: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm
zabbix_agent_packages:
  - "zabbix-agent"

zabbix_agent_install_from_source: false

zabbix_agent_hostname: "{{ ansible_hostname | d() }}"
zabbix_agent_server_host: "123.0.22.123"

zabbix_agent_conf_path: "/etc/zabbix" 
